export enum KeyCode {
  SHIFT = 16,
  CONTROL = 17,
  OPTION = 18,
  CAPSLOCK = 20,
  ARROW_LEFT = 37,
  ARROW_UP = 38,
  ARROW_RIGHT = 39,
  ARROW_DOWN = 40,
  COMMAND = 91,
  RIGHT_WINDOW_KEY = 92,
  RIGHT_COMMAND = 93
}
